### ISSUE TITLE
Overlay Drawing on tkVideoPlayer

### ISSUE THREAD

**Issue by Meghansh-Maurya** [PaulleDemon/tkVideoPlayer#25]
how to overlay drawing on tkvideoplayer?
I have already tried canvas.lower()

**Comment by PaulleDemon** [comment]
Hi @Meghansh-Maurya,  You cannot draw over window objects in Tkinter canvas. You can clone this project, then instead of inheriting from Label, inherit from Canvas, then use `canvas.create_image(x, y, anchor=NW, image=image)` to draw the video into the canvas; you may then be able to overlay other drawings.

**Comment by zaynabtariq** [comment]
Hi @PaulleDemon, I tried doing this but I keep getting an error. How do make this work?
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
    self.run()
  File "threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "tkvideoplayer.py", line 131, in _load
    self._set_frame_size()
  File "tkvideoplayer.py", line 99, in _set_frame_size
    self.config(width=150, height=100, image=self.current_imgtk)
  File "__init__.py", line 1646, in configure        
    return self._configure('configure', cnf, kw)
  File "__init__.py", line 1636, in _configure       
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-image"
