### ISSUE TITLE
Unable to install the new version 2.5 on windows

### ISSUE THREAD

**Issue by oseijoel6111** [PaulleDemon/tkVideoPlayer#44]
I tried several and also tried installing it on a different system that uses Windows OS but didn't work

 error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      Compiling av\buffer.pyx because it changed.
      [1/1] Cythonizing av\buffer.pyx
      Compiling av\bytesource.pyx because it changed.
      [1/1] Cythonizing av\bytesource.pyx
      Compiling av\descriptor.pyx because it changed.
      [1/1] Cythonizing av\descriptor.pyx
      Compiling av\dictionary.pyx because it changed.
      [1/1] Cythonizing av\dictionary.pyx
      Compiling av\enum.pyx because it changed.
      [1/1] Cythonizing av\enum.pyx
      Compiling av\error.pyx because it changed.
      [1/1] Cythonizing av\error.pyx
      Compiling av\format.pyx because it changed.
      [1/1] Cythonizing av\format.pyx
      Compiling av\frame.pyx because it changed.
      [1/1] Cythonizing av\frame.pyx
      performance hint: av\logging.pyx:232:5: Exception check on 'log_callback' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef const char *log_context_name(void *ptr) nogil:
          cdef log_context *obj = <log_context*>ptr
          return obj.name

      cdef lib.AVClass log_class
      log_class.item_name = log_context_name
                            ^
      ------------------------------------------------------------

      av\logging.pyx:216:22: Cannot assign type 'const char *(void *) except? NULL nogil' to 'const char *(*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'const char *(void *) except? NULL nogil'.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

      # Start the magic!
      # We allow the user to fully disable the logging system as it will not play
      # nicely with subinterpreters due to FFmpeg-created threads.
      if os.environ.get('PYAV_LOGGING') != 'off':
          lib.av_log_set_callback(log_callback)
                                  ^
      ------------------------------------------------------------

      av\logging.pyx:351:28: Cannot assign type 'void (void *, int, const char *, va_list) except * nogil' to 'av_log_callback'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, int, const char *, va_list) except * nogil'.
      Compiling av\logging.pyx because it changed.
      [1/1] Cythonizing av\logging.pyx
      Traceback (most recent call last):
        File "C:\Users\CodeWithJoel\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\CodeWithJoel\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\CodeWithJoel\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\CodeWithJoel\AppData\Local\Temp\pip-build-env-aihy54j2\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\CodeWithJoel\AppData\Local\Temp\pip-build-env-aihy54j2\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\CodeWithJoel\AppData\Local\Temp\pip-build-env-aihy54j2\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\CodeWithJoel\AppData\Local\Temp\pip-build-env-aihy54j2\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 156, in <module>
        File "C:\Users\CodeWithJoel\AppData\Local\Temp\pip-build-env-aihy54j2\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\CodeWithJoel\AppData\Local\Temp\pip-build-env-aihy54j2\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: av\logging.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by PaulleDemon** [comment]
Hi, thanks for the detailed information. Can you check if you are able to install the previous version?

**Comment by oseijoel6111** [comment]
Yh am able to install the old version but no sound, can I contribute??

**Comment by oseijoel6111** [comment]
Sorry I mistakenly close the issue but can I contribute??

**Comment by PaulleDemon** [comment]
I am running Linux, I would like someone to confirm if the same is happening  @havetc. You are more the welcome to contribute. https://github.com/PaulleDemon/tkVideoPlayer/issues/2.

**Comment by havetc** [comment]
@oseijoel6111 
`pip install tkVideoPlayer==2.5` works fine on windows with python 3.10.
It seems that you are trying to build av package instead of downloading it, and that build fails.
Are you on python 3.6 ? It seems that av package version 9.1.1 only has pre-built binaries from version 3.7 to 3.10, I would suggest upgrading python version. Otherwise, you would need to check with the av package team for help with this build error.

@PaulleDemon It's not very nice of you to ask me for help after having ignored some of my messages for months / rejected pull-request confirmed to solve some issues as discussions in #15 showed. Please don't do it anymore.

**Comment by PaulleDemon** [comment]
Hi @havetc I am sorry you felt that way. I was working in a startup and was quite packed during those months. The pull request wasn't rejected the pull request is already merged in with 2.5. If you are talking about #34  Weren't the [#28](https://github.com/PaulleDemon/tkVideoPlayer/pull/28) and [#34](https://github.com/PaulleDemon/tkVideoPlayer/pull/34) doing the same thing?
I am sorry again if I have caused any trouble.

**Comment by PaulleDemon** [comment]
@oseijoel6111 I'll mark this as closed for now. If you have any further problems feel free to ask
